# otel-collector-config.yaml
receivers:
  otlp:
    protocols:
      grpc: # Protocolo gRPC para traces e métricas (Serviços A e B enviarão via gRPC)
        endpoint: 0.0.0.0:4317
      http: # Protocolo HTTP para traces e métricas
        endpoint: 0.0.0.0:4318

processors:
  batch:
    # Processa traces em lotes para exportação mais eficiente
    timeout: 10s
    send_batch_size: 1000

exporters:
  zipkin:
    # Exporta os traces para o Zipkin.
    endpoint: http://zipkin:9411/api/v2/spans # Nome do serviço Zipkin no Docker Compose
  debug: # <--- CHANGED FROM 'logging' TO 'debug'
    # Exporta traces para o console do Collector (útil para depuração)
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [zipkin, debug] # <--- CHANGED FROM 'logging' TO 'debug'